# Generated by Django 5.1.1 on 2024-09-12 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Kategoriya nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Yangilik nomi')),
                ('slug', models.SlugField(max_length=255, verbose_name='Sluglar')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Ma'lumoti")),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/', verbose_name='Rasmi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shish vaqti")),
                ('is_active', models.BooleanField(default=True, verbose_name='Saytga chiqarish')),
                ('is_popular', models.BooleanField(default=True, verbose_name='Mashxur chiqarish')),
                ('is_trending', models.BooleanField(default=True, verbose_name='Sara yangiliklar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Maqola kategoriyasi')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
